name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
          
      - name: Get current release version
        id: version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: HamedSY/FullTextSearchTDD

      - name: Build library and generate NuGet Package
        run: dotnet pack -c Release -o artifacts -p:PackageVersion=${{ steps.version.outputs.release }}
        working-directory: FullTextSearchTDD
        
      - name: Publish NuGet Package
        run: dotnet nuget push ./**/*.symbols.nupkg --api-key oy2iai6bivekrwbcvu6azvj4aspjuhaubnb7lhera4pcvi -s https://api.nuget.org/v3/index.json